### ISSUE TITLE
Could you provide some instructions for creating the electron density function database?

### ISSUE THREAD

**Issue by seongsukim-ml** [ulissigroup/charge-density-models#17]
Hi, I am trying to reproduce your model, but it seems hard to find the description of the dataset.

Could you provide the direct links to download the dft datset of OCP (i.e. google drive or figshare) or give detailed instruction to reproduce the dataset?

Thank you.

**Comment by emsunshine** [comment]
Hello,

Thank you for your interest in my work!

[I have just added a script ](https://github.com/ulissigroup/charge-density-models/pull/18) that you may find helpful for converting the ASE DBs to VASP input files.

Be advised that running all of the calculations and storing the CHGCARs will require about 3TB of disk space. Once you have the CHGCARs you can [compress it back to a DB](https://github.com/ulissigroup/charge-density-models/blob/bac64ff98dcfb015d19be1cbe9d3ae435600f999/cdm/utils/chg_db.py#L77) which will require about 1TB.

**Comment by zhiyuwang0911** [comment]
Hi, I did't find the Kspacings or KPOINTS information to obtain the CHGCAR in the script you mentioned.

**Comment by emsunshine** [comment]
You may be interested in [this work](https://pubs.rsc.org/en/content/articlehtml/2024/cy/d4cy00615a) which provides more details about the DFT settings of OC20, including KPOINTS.

The number of kpoints in a dimension of the cell is approximately: 40 angstroms divided by the length of the cell lattice vector.
