### ISSUE TITLE
Restarting training?

### ISSUE THREAD

**Issue by BurnerJ** [ulissigroup/charge-density-models#20]
Hi there,

Is there a way to properly restart training from a previous checkpoint? Any help with this is greatly appreciated!

**Comment by emsunshine** [comment]
Hi,

If you can load the checkpoint, this should be possible. Try assigning the `.model` attribute of the trainer after it has been loaded and before calling `.train()`. I am not sure how much of the metadata from the previous run will be carried over, but you should at least still have the model weights of the previous checkpoint to start from.

**Comment by BurnerJ** [comment]
Thanks for your rapid response! I was getting confused with the module. attributes that were not being found in my loaded state_dict (I was working off the example of loading models from the inference code). After doing some reading online, I figured it out. I'll post here what I did in case anyone else has issues loading old models for training:

`
path = "checkpoint.pt"
state_dict = torch.load(path)['state_dict']
trainer.model.load_state_dict(sd)
trainer.train()

`
